package utils

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

func EnsureParent(ctx context.Context, db *sql.DB) error {
	const q = `
CREATE TABLE IF NOT EXISTS short_urls (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  long_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS click_events (
  occurred_at TIMESTAMPTZ NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  short_url_id BIGINT NOT NULL,
  referrer TEXT NULL,
  user_agent TEXT NULL,
  PRIMARY KEY (occurred_at, id)
) PARTITION BY RANGE (occurred_at);

CREATE INDEX IF NOT EXISTS idx_click_events_url_time
  ON click_events (short_url_id, occurred_at);
`

	_, err := db.ExecContext(ctx, q)
	if err != nil {
		return fmt.Errorf("failed to create tables: %w", err)
	}
	return nil
}

// EnsureMonthlyPartitions fromMonth を含め months 分の月次パーティション作成
func EnsureMonthlyPartitions(ctx context.Context, db *sql.DB, fromMonth time.Time, months int) error {
	// 月初
	start := time.Date(fromMonth.Year(), fromMonth.Month(), 1, 0, 0, 0, 0, time.UTC)

	for i := 0; i < months; i++ {
		from := start.AddDate(0, i, 0)
		to := start.AddDate(0, i+1, 0)

		partName := fmt.Sprintf("click_events_%04d_%02d", from.Year(), int(from.Month()))
		q := fmt.Sprintf(`
	CREATE TABLE IF NOT EXISTS %s
	  PARTITION OF click_events
	  FOR VALUES FROM ('%s') TO ('%s');
`, partName, from.Format("2006-01-02"), to.Format("2006-01-02"))

		if _, err := db.ExecContext(ctx, q); err != nil {
			return fmt.Errorf("failed to create partition: %w", err)
		}
	}
	return nil
}
